name: svg_microservice
type: nodejs:10

dependencies:
  nodejs:
    pm2: "^2.0.0"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start index.js --no-daemon"
    #in this setup you will find your application stdout and stderr in /app/run/logs
mounts:
  "/run": "shared:files/run"

disk: 512
